export type LandingLanguage = 'tr' | 'en';

type CopyTree = Record<string, string>;

export const landingCopy: Record<LandingLanguage, CopyTree> = {
  tr: {
    'nav.brandAria': 'Mentora ana sayfa',
    'nav.howItWorks': 'Nasıl Çalışır?',
    'nav.trust': 'Güven',
    'nav.ai': 'Yapay Zekâ',
    'nav.becomeMentor': 'Mentor Ol',
    'nav.login': 'Giriş Yap',
    'nav.getStarted': 'Hemen Başla',
    'hero.sectionLabel': 'Giriş ve tanıtım',
    'hero.badge': 'Yeni Nesil Eğitim Platformu',
    'hero.title': 'Yeni Nesil Online Özel Ders Platformu',
    'hero.description':
      'Mentora, öğrencileri güvenilir üniversite öğrencisi mentorlarla buluşturur; ders sonrası yapay zekâ destekli özet, quiz ve performans raporlarıyla öğrenme sürecini görünür hale getirir.',
    'hero.startLearning': 'Ders Almaya Başla',
    'hero.applyMentor': 'Mentor Olarak Başvur',
    'hero.todayLesson': 'Bugünkü Ders',
    'hero.live': 'Canlı',
    'hero.math': 'Matematik',
    'hero.grade7': '7. Sınıf',
    'hero.mentorLabel': 'Mentor: Elif K.',
    'hero.mentorUni': 'İTÜ Matematik Bölümü',
    'hero.summaryReady': 'Ders Özeti Hazırlandı',
    'hero.miniQuiz': 'Mini Quiz: 5 soru',
    'hero.performance': 'Performans: Gelişiyor',
    'hero.trustBadge1': 'Kimliği Doğrulanmış Mentorlar',
    'hero.trustBadge2': 'Veli Takip Paneli',
    'hero.trustBadge3': 'Yapay Zekâ Destekli Raporlar',
    'hero.trustBadge4': 'Online Canlı Ders',
    'problem.title': 'Özel ders süreci çoğu aile için hâlâ belirsiz',
    'problem.card1.title': 'Kalite standardı yok',
    'problem.card1.desc':
      'Aileler çoğu zaman öğretmenin güvenilirliğini, ders kalitesini ve öğrencinin gerçekten ilerleyip ilerlemediğini takip etmekte zorlanır.',
    'problem.card2.title': 'Öğrenciyle bağ kurmak zor',
    'problem.card2.desc':
      'Yaş ve iletişim farkı, öğrencinin motivasyonunu düşürebilir. Mentora, öğrenciye daha yakın rol modellerle bu bağı güçlendirir.',
    'problem.card3.title': 'Ders sonrası takip eksik',
    'problem.card3.desc':
      'Bir ders bittikten sonra hangi konular işlendi, öğrenci nerede zorlandı ve ne tekrar edilmeli soruları genellikle cevapsız kalır.',
    'how.title': 'Mentora Nasıl Çalışır?',
    'how.subtitle': 'Basit, güvenli ve takip edilebilir bir öğrenme süreci',
    'how.step1.title': 'Mentor başvurur',
    'how.step1.desc': 'Akademik bilgi ve kimlik doğrulama süreci tamamlanır.',
    'how.step2.title': 'Öğrenci veya veli ders seçer',
    'how.step2.desc': 'Ders konusu, seviye ve uygun saatlere göre mentor bulunur.',
    'how.step3.title': 'Online ders gerçekleşir',
    'how.step3.desc': 'Öğrenci ve mentor canlı ders üzerinden buluşur.',
    'how.step4.title': 'Ders çıktıları oluşturulur',
    'how.step4.desc': 'Ders özeti, işlenen konular, mini quiz ve performans raporu hazırlanır.',
    'how.step5.title': 'Veli gelişimi takip eder',
    'how.step5.desc': 'Veli, öğrencinin ilerlemesini şeffaf şekilde görebilir.',
    'ai.badge': 'Yapay zekâ destekli',
    'ai.title': 'Yapay zekâ ile ders sonrası takip artık çok daha net',
    'ai.subtitle':
      'Mentora, her dersin ardından öğrenme sürecini ölçülebilir ve takip edilebilir hale getiren akıllı çıktılar üretir.',
    'ai.feature1.title': 'Ders Özeti',
    'ai.feature1.desc': 'Ders boyunca işlenen konular sade ve anlaşılır şekilde özetlenir.',
    'ai.feature2.title': 'Performans Raporu',
    'ai.feature2.desc':
      'Öğrencinin güçlü olduğu alanlar, zorlandığı konular ve gelişim ihtiyacı analiz edilir.',
    'ai.feature3.title': 'Mini Quiz',
    'ai.feature3.desc': 'İşlenen konulara göre kısa tekrar quizleri oluşturulur.',
    'ai.feature4.title': 'Eksik Konu Analizi',
    'ai.feature4.desc':
      'Öğrencinin anlamakta zorlandığı noktalar belirlenir ve tekrar önerileri sunulur.',
    'trust.title': "Güven, Mentora'nın merkezinde",
    'trust.description':
      "Mentora'da mentorlar kimlik ve akademik doğrulama süreçlerinden geçer. Veliler dersleri, raporları ve öğrenci gelişimini güvenli bir panel üzerinden takip edebilir.",
    'trust.item1': 'Kimlik doğrulama',
    'trust.item2': 'Akademik belge kontrolü',
    'trust.item3': 'Veli onayı',
    'trust.item4': 'Şeffaf puanlama ve ders geçmişi',
    'trust.dataNote':
      'Öğrenci verileri güvenli şekilde saklanır ve süreçler veli onayıyla ilerler.',
    'trust.badgeSsl': 'SSL',
    'trust.badgeKvkk': 'KVKK',
    'trust.badgeVerified': 'Doğrulanmış',
    'trust.kvkk': 'KVKK Uyumlu',
    'trust.kvkkDesc': 'Veri güvenliği standartlarına uygun',
    'value.title': 'Herkes için net bir değer',
    'value.students': 'Öğrenciler için',
    'value.students.1': 'Daha yakın yaşta mentorlarla rahat iletişim',
    'value.students.2': 'Online ders kolaylığı',
    'value.students.3': 'Quiz ve özetlerle tekrar imkanı',
    'value.parents': 'Veliler için',
    'value.parents.1': 'Güvenilir mentor havuzu',
    'value.parents.2': 'Ders sonrası gelişim raporları',
    'value.parents.3': 'Şeffaf süreç takibi',
    'value.mentors': 'Mentorlar için',
    'value.mentors.1': 'Bilgini gelire dönüştürme',
    'value.mentors.2': 'Esnek saatlerde ders verme',
    'value.mentors.3': 'Güvenilir platformda profil oluşturma',
    'mentorCta.title': 'Üniversite öğrencisi misin? Mentor olarak başvur.',
    'mentorCta.description':
      'Akademik bilgini paylaş, öğrencilerin gelişimine katkı sağla ve esnek saatlerde gelir elde et.',
    'mentorCta.button': 'Mentor Başvurusu Yap',
    'finalCta.title':
      'Özel ders deneyimini daha güvenilir, takip edilebilir ve akıllı hale getirin.',
    'finalCta.startLearning': 'Ders Almaya Başla',
    'finalCta.applyMentor': 'Mentor Olarak Başvur',
    'finalCta.earlyAccess': 'Mentora şu anda erken erişim sürecindedir.',
    'footer.description':
      'Mentora, öğrenciler, veliler ve üniversite öğrencisi mentorlar için yeni nesil online eğitim platformudur.',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Kullanım Şartları',
    'footer.mentorApply': 'Mentor Başvurusu',
    'footer.contact': 'İletişim',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.madeIn': "Türkiye'de yapıldı",
  },
  en: {
    'nav.brandAria': 'Mentora home',
    'nav.howItWorks': 'How It Works?',
    'nav.trust': 'Trust',
    'nav.ai': 'AI Features',
    'nav.becomeMentor': 'Become a Mentor',
    'nav.login': 'Log in',
    'nav.getStarted': 'Get Started',
    'hero.sectionLabel': 'Welcome and introduction',
    'hero.badge': 'Next-Gen Education Platform',
    'hero.title': 'Next-Generation Online Tutoring Platform',
    'hero.description':
      'Mentora connects students with trusted university student mentors; makes the learning process visible with AI-powered summaries, quizzes, and performance reports after each lesson.',
    'hero.startLearning': 'Start Learning',
    'hero.applyMentor': 'Apply as Mentor',
    'hero.todayLesson': "Today's Lesson",
    'hero.live': 'Live',
    'hero.math': 'Mathematics',
    'hero.grade7': '7th Grade',
    'hero.mentorLabel': 'Mentor: Elif K.',
    'hero.mentorUni': 'ITU Mathematics Dept.',
    'hero.summaryReady': 'Lesson Summary Ready',
    'hero.miniQuiz': 'Mini Quiz: 5 questions',
    'hero.performance': 'Performance: Improving',
    'hero.trustBadge1': 'Verified Mentors',
    'hero.trustBadge2': 'Parent Dashboard',
    'hero.trustBadge3': 'AI-Powered Reports',
    'hero.trustBadge4': 'Live Online Classes',
    'problem.title': 'Private tutoring is still unclear for most families',
    'problem.card1.title': 'No quality standards',
    'problem.card1.desc':
      'Families often struggle to track teacher reliability, lesson quality, and whether the student is actually progressing.',
    'problem.card2.title': 'Hard to connect with students',
    'problem.card2.desc':
      'Age and communication gaps can lower student motivation. Mentora strengthens this connection with closer role models.',
    'problem.card3.title': 'No post-lesson follow-up',
    'problem.card3.desc':
      'After a lesson ends, questions about what was covered, where the student struggled, and what needs review often go unanswered.',
    'how.title': 'How Does Mentora Work?',
    'how.subtitle': 'Simple, secure, and trackable learning process',
    'how.step1.title': 'Mentor applies',
    'how.step1.desc': 'Academic info and identity verification is completed.',
    'how.step2.title': 'Student or parent selects lesson',
    'how.step2.desc': 'Find a mentor based on subject, level, and available times.',
    'how.step3.title': 'Online lesson takes place',
    'how.step3.desc': 'Student and mentor meet via live session.',
    'how.step4.title': 'Lesson outputs generated',
    'how.step4.desc':
      'Lesson summary, topics covered, mini quiz, and performance report are prepared.',
    'how.step5.title': 'Parent tracks progress',
    'how.step5.desc': 'Parents can transparently see student progress.',
    'ai.badge': 'AI-Powered',
    'ai.title': 'AI makes post-lesson tracking much clearer',
    'ai.subtitle':
      'Mentora generates smart outputs after each lesson, making the learning process measurable and trackable.',
    'ai.feature1.title': 'Lesson Summary',
    'ai.feature1.desc': 'Topics covered during the lesson are summarized clearly and concisely.',
    'ai.feature2.title': 'Performance Report',
    'ai.feature2.desc': "Student's strengths, challenges, and development needs are analyzed.",
    'ai.feature3.title': 'Mini Quiz',
    'ai.feature3.desc': 'Short review quizzes are generated based on covered topics.',
    'ai.feature4.title': 'Gap Analysis',
    'ai.feature4.desc':
      'Points where student struggled are identified with review recommendations.',
    'trust.title': 'Trust is at the heart of Mentora',
    'trust.description':
      'At Mentora, mentors go through identity and academic verification. Parents can track lessons, reports, and student progress through a secure dashboard.',
    'trust.item1': 'Identity verification',
    'trust.item2': 'Academic document check',
    'trust.item3': 'Parent approval',
    'trust.item4': 'Transparent ratings & lesson history',
    'trust.dataNote':
      'Student data is stored securely and processes proceed with parent approval.',
    'trust.badgeSsl': 'SSL',
    'trust.badgeKvkk': 'GDPR',
    'trust.badgeVerified': 'Verified',
    'trust.kvkk': 'GDPR Compliant',
    'trust.kvkkDesc': 'Compliant with data security standards',
    'value.title': 'Clear value for everyone',
    'value.students': 'For Students',
    'value.students.1': 'Comfortable communication with closer-age mentors',
    'value.students.2': 'Convenience of online lessons',
    'value.students.3': 'Review with quizzes and summaries',
    'value.parents': 'For Parents',
    'value.parents.1': 'Trusted mentor pool',
    'value.parents.2': 'Post-lesson progress reports',
    'value.parents.3': 'Transparent process tracking',
    'value.mentors': 'For Mentors',
    'value.mentors.1': 'Turn your knowledge into income',
    'value.mentors.2': 'Teach at flexible hours',
    'value.mentors.3': 'Build your profile on a trusted platform',
    'mentorCta.title': 'Are you a university student? Apply as a mentor.',
    'mentorCta.description':
      'Share your academic knowledge, contribute to student development, and earn income at flexible hours.',
    'mentorCta.button': 'Apply as Mentor',
    'finalCta.title':
      'Make your tutoring experience more reliable, trackable, and intelligent.',
    'finalCta.startLearning': 'Start Learning',
    'finalCta.applyMentor': 'Apply as Mentor',
    'finalCta.earlyAccess': 'Mentora is currently in early access.',
    'footer.description':
      'Mentora is a next-generation online education platform for students, parents, and university student mentors.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.mentorApply': 'Mentor Application',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.madeIn': 'Made in Turkey',
  },
};

export type LandingCopy = (key: string) => string;

export function createLandingCopy(lang: LandingLanguage): LandingCopy {
  const dict = landingCopy[lang];
  return (key) => dict[key] ?? key;
}
